apiVersion: cloud.exascale.keti/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: exascale-resource-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: exascale-resource-controller
  name: cluster-sample
spec:
  # TODO(user): Add fields here
