apiVersion: metric.exascale.keti/v1
kind: GPU
metadata:
  labels:
    app.kubernetes.io/name: gpu
    app.kubernetes.io/instance: gpu-sample
    app.kubernetes.io/part-of: exascale-resource-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: exascale-resource-controller
  name: gpu-sample
spec:
  # TODO(user): Add fields here
