apiVersion: metric.exascale.keti/v1
kind: GenericMetric
metadata:
  labels:
    app.kubernetes.io/name: genericmetric
    app.kubernetes.io/instance: genericmetric-sample
    app.kubernetes.io/part-of: exascale-resource-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: exascale-resource-controller
  name: genericmetric-sample
spec:
  # TODO(user): Add fields here
