apiVersion: metric.exascale.keti/v1
kind: Collector
metadata:
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/instance: collector-sample
    app.kubernetes.io/part-of: exascale-resource-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: exascale-resource-controller
  name: collector
spec:
  # TODO(user): Add fields here
